const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';
const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO';
const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR';

export {
    AGREGAR_PRODUCTO,
    AGREGAR_PRODUCTO_EXITO,
    AGREGAR_PRODUCTO_ERROR,
    COMENZAR_DESCARGA_PRODUCTOS,
    DESCARGA_PRODUCTOS_EXITO,
    DESCARGA_PRODUCTOS_ERROR,
    OBTENER_PRODUCTO_ELIMINAR,
    PRODUCTO_ELIMINADO_EXITO,
    PRODUCTO_ELIMINADO_ERROR,
    OBTENER_PRODUCTO_EDITAR,
    PRODUCTO_EDITADO_EXITO,
    PRODUCTO_EDITADO_ERROR,
    COMENZAR_EDICION_PRODUCTO

}